version: '3.1'

services:
  php:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./index.php:/var/www/html/index.php
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opdracht_cloud
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: